services:
  - type: web
    name: etoas-app
    env: ruby
    plan: free
    buildCommand: "corepack enable && bundle install && yarn install && yarn build"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: NODE_VERSION
        value: 18.19.1
      - key: DATABASE_URL
        fromDatabase:
          name: etoas-db
          property: connectionString
      - key: SECRET_KEY_BASE
        value: 471c04500177f922bed6799b0ab65b881a82fdf9f882c02e244e012c4f253d17806635298d0f92c81d64df942e8df3e904a736177148dab424e2f689aca21f49
      - key: RAILS_ENV
        value: production
    databases:
      - name: etoas-db
    postDeploy:
      command: "bundle exec rails db:migrate"
