services:
  - type: web
    name: etoas-app
    env: ruby
    plan: free
    buildCommand: "bundle install && yarn install && bundle exec rails assets:precompile"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: etoas-db
          property: connectionString
    databases:
      - name: etoas-db
    postDeploy:
      command: "bundle exec rails db:migrate"
